Repository youngmonkeys/ezyfox-server, pull requests merged in 2023-08, with the labels that each got.

#117 Fix demo URL not found
  README.md
Labels: bug, good first pull request, documentation

#115 Restructure README
  README.md
  images/ezyfox-server-architecture.png
Labels: documentation, big change

#124 improve EzyNioSocketAcceptor
  ezyfox-server-nio/src/main/java/com/tvd12/ezyfoxserver/nio/EzySocketServerBootstrap.java
  ezyfox-server-nio/src/main/java/com/tvd12/ezyfoxserver/nio/socket/EzyNioSocketAcceptor.java
  ezyfox-server-nio/src/test/java/com/tvd12/ezyfoxserver/nio/testing/socket/EzyNioSocketAcceptorTest.java
  ezyfox-server-nio/src/test/java/com/tvd12/ezyfoxserver/nio/testing/socket/EzyNioSocketReaderTest.java
Labels: enhancement, 2
